"""Add case workflow fields

Revision ID: 798972dfe6a2
Revises: 
Create Date: 2026-03-17 16:15:20.163991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798972dfe6a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('cases', sa.Column('tenure', sa.Integer(), nullable=True))
    op.add_column('cases', sa.Column('deal_status', sa.Enum('DRAFT', 'LISTED', 'UNDER_CONTRACT', 'SETTLED', 'CLOSED', name='deal_status'), nullable=True))
    op.add_column('cases', sa.Column('approved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'approved_at')
    op.drop_column('cases', 'deal_status')
    op.drop_column('cases', 'tenure')
    op.drop_column('cases', 'interest_rate')
    # ### end Alembic commands ###
